### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zqm64** [exynos5410/manifest#1]
more info:http://zqmsjenkins.ngrok.cc/job/LineageOS-Builds/job/14.1/job/i9500/2/console

+ chmod +x patch.sh
+ source patch.sh
++ cd bootable/recovery-twrp
++ git fetch https://gerrit.omnirom.org/android_bootable_recovery refs/changes/96/22096/3
From https://gerrit.omnirom.org/android_bootable_recovery
 * branch            refs/changes/96/22096/3 -> FETCH_HEAD
++ git cherry-pick FETCH_HEAD
[detached HEAD 87e1380] Fix for LineageOS build
 Author: dianlujitao <dianlujitao@lineageos.org>
 Date: Fri Feb 24 15:32:57 2017 +0800
 2 files changed, 18 insertions(+), 1 deletion(-)
++ git fetch https://gerrit.omnirom.org/android_bootable_recovery refs/changes/20/23520/2
From https://gerrit.omnirom.org/android_bootable_recovery
 * branch            refs/changes/20/23520/2 -> FETCH_HEAD
++ git cherry-pick FETCH_HEAD
error: could not apply a0ac111... fix use of TW_USE_MINUI_CUSTOM_FONTS
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
Recorded preimage for 'minui/minui.h'
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by Alberto96** [comment]
Fixed: https://github.com/exynos5410/manifest/commit/7d7b584230bddeee591ffa82872ce9e670040e2b

Thanks for the report.
